version: '3.8'

services:
  frontend:
    build:
      context: ./ # Since your frontend files and the .yml file are in the same directory
      dockerfile: Dockerfile # This should point to the frontend Dockerfile
    container_name: starteryou-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://54.196.202.145:3000
    networks:
      - starteryou-network

networks:
  starteryou-network:
    driver: bridge
